spring:
  application:
    name: wm
  datasource:
    wmdb1:
      jdbc-url: jdbc:mysql://localhost:3307/wmdb1?serverTimezone=Asia/Seoul&characterEncoding=utf8
      username: wm
      password: "!ckdtprl10!"
      driver-class-name: com.mysql.cj.jdbc.Driver
      auto-commit: false
    wmdb2:
      jdbc-url: jdbc:mysql://localhost:3307/wmdb1?serverTimezone=Asia/Seoul&characterEncoding=utf8
      username: wm
      password: "!ckdtprl20!"
      driver-class-name: com.mysql.cj.jdbc.Driver
      auto-commit: false
server:
  port: 8080

app:
  frontendBaseUrl: "http://localhost:5173"
  jwt:
    issuer: wm
    secret: wm-local-secret-please-make-it-longer-than-32bytes-123456  # 환경변수로 주입 권장
    accessMinutes: 30
    refreshDays: 30
  cookie:
    secure: false                 # 로컬은 false, 운영(https)은 true
    sameSite: Lax               # 크로스사이트 요구 시 None(+Secure 필수) 고려
  kakao:
    clientId: ${KAKAO_CLIENT_ID}
    redirectUri: http://localhost:5173/auth/kakao/callback

